name: Upstream Sync

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write  # 仅保留必要的写入权限

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}  # 仅在Fork仓库运行

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史，避免浅克隆导致的问题

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/senshinya/MoonTV.git
          git fetch upstream

      - name: Merge upstream changes with unrelated histories allowed
        run: |
          # 尝试正常合并，如果失败则允许不相关历史合并
          if ! git merge upstream/main; then
            echo "Normal merge failed, attempting to merge with unrelated histories"
            git merge upstream/main --allow-unrelated-histories
          fi

      - name: Push changes to fork
        run: |
          git push origin main

      - name: Clean up old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 5
